# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
#%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

1.15.0


### Set random seed

In [0]:
tf.random.set_seed(42)

AttributeError: ignored

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
# Import necessary packages
import numpy as np
import pandas as pd

In [0]:
from sklearn.datasets import load_iris
iris_df = load_iris()

In [0]:
#import pandas as pd
#import io
#iris_data= pd.read_csv(io.StringIO(uploaded['iris.csv'].decode('utf-8')))

In [0]:
list(iris_df.target_names)

['setosa', 'versicolor', 'virginica']

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
iris_features = iris_df.data
iris_target = iris_df.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_features, iris_target, test_size=0.25, random_state=42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from tensorflow.keras.utils import to_categorical
y_train=to_categorical(y_train,3)
y_test=to_categorical(y_test,3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Flatten,Activation
from sklearn import metrics

Using TensorFlow backend.


In [0]:
#Initialize the Sequence
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
# Add an input layer
model.add(Dense(12,input_shape=(4,),activation='softmax'))
#Add an output layer
model.add(Dense(3,activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
for layer in model.layers:
    print(layer.output_shape)

(None, 12)
(None, 3)


In [0]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 12)                60        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 39        
Total params: 99
Trainable params: 99
Non-trainable params: 0
_________________________________________________________________
None


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [0]:
fit_model = model.fit(X_train,y_train,epochs=100,batch_size=1,verbose=1)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/100





112/112 [==============================] - 1s 6ms/step - loss: 1.0116 - acc: 0.5446
Epoch 2/100
112/112 [==============================] - 0s 1ms/step - loss: 0.9571 - acc: 0.5714
Epoch 3/100
112/112 [==============================] - 0s 978us/step - loss: 0.9022 - acc: 0.7589
Epoch 4/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8467 - acc: 0.7143
Epoch 5/100
112/112 [==============================] - 0s 1ms/step - loss: 0.7978 - acc: 0.6786
Epoch 6/100
112/112 [==============================] - 0s 1ms/step - loss: 0.7548 - acc: 0.6786
Epoch 7/100
112/112 [==============================] - 0s 986us/step - loss: 0.7187 - acc: 0.6964
Epoch 8/100
112/112 [==============================] - 0s 1ms/step - loss: 0.6887 - acc: 0.7679
Epoch 9/100
112/112 [==============================] - 0s 971us/step - loss: 0.6630 - acc: 0.7589
Epoch 10/100
112/112 [======

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
Predict = np.round(model.predict(X_test))
Predict[0:10]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
score =model.evaluate(X_test,y_test,verbose=1)
print(score)

38/38 [==============================] - 0s 156us/step
[0.26818402111530304, 0.9736842105263158]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [5]:
# run this cell to upload file if you are using google colab
from google.colab import files
uploaded=files.upload()

Saving prices.csv to prices (1).csv


In [15]:
import numpy as np
import pandas as pd
import io

prices_df = pd.read_csv(io.StringIO(uploaded['prices.csv'].decode('utf-8')))
prices_df.head(5)

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
prices_df.drop(['date','symbol'],axis=1,inplace=True)

In [17]:
prices_df.head(5)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
prices_data = prices_df.iloc[0:1000,:]

In [19]:
prices_data.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = prices_data.drop(['volume'],axis=1)
Y = prices_data['volume']

In [0]:
Y = Y/1000000

In [22]:
Y.head(5)

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X= np.array(X)
Y=np.array(Y)

In [0]:
#X=X.astype('float32')

In [0]:
#y=y.astype('float32')

In [24]:
print("X[0]: ",X[0])
print("Y[0]: ",Y[0])
print("Len of X:{} and length of Y:{}".format(len(X), len(Y)))

X[0]:  [123.43     125.839996 122.309998 126.25    ]
Y[0]:  2.1636
Len of X:1000 and length of Y:1000


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [25]:
X_normalized = tf.math.l2_normalize(X,axis=0)
X_normalized

<tf.Tensor: shape=(1000, 4), dtype=float64, numpy=
array([[0.04405065, 0.0448811 , 0.04406771, 0.04469663],
       [0.04469661, 0.04279112, 0.04321381, 0.04444527],
       [0.04153459, 0.04099716, 0.04140873, 0.04239187],
       ...,
       [0.01010706, 0.01026088, 0.01009187, 0.01019968],
       [0.01570306, 0.01597802, 0.01576292, 0.01586421],
       [0.01287651, 0.01324606, 0.01297423, 0.01318064]])>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w = tf.Variable(tf.zeros(shape=(4,1)))
b = tf.Variable(tf.zeros(shape=(1)))
w = tf.dtypes.cast(w, tf.float64)
b = tf.dtypes.cast(b, tf.float64)

In [27]:
print("weight: ",w)
print("bias: ",b)

weight:  tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float64)
bias:  tf.Tensor([0.], shape=(1,), dtype=float64)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(X,w,b):
    yhat = tf.add(tf.matmul(X,w),b)
    return yhat
    

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss_function(Y_actual, Y_predicted):
  error = Y_actual - Y_predicted
  loss = tf.reduce_mean(tf.square(error))
  return loss

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X,Y, w,b,learning_rate = 0.1):
  
  with tf.GradientTape() as tape:
    tape.watch([w,b])
    Yhat = prediction(X, w,b)
    loss = loss_function(Y, Yhat)
  
  #evalute the gradient with the respect to the paramters
  dW, db = tape.gradient(loss, [w, b])
  
  #update the paramters using Gradient Descent  
  w = w - learning_rate * dW
  b = b - learning_rate * db

  return w, b

In [0]:
#X= np.array([prices_features])
#y= np.array([prices_label])

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [33]:
epochs = 1001
for i in range(epochs):
  w, b = train(X_normalized,Y, w,b)
  print("Training Loss on iteration ", i, loss_function(Y, prediction(X_normalized, w,b)).numpy())


Training Loss on iteration  0 209.04581679745903
Training Loss on iteration  1 209.04581675915944
Training Loss on iteration  2 209.04581672088628
Training Loss on iteration  3 209.0458166826397
Training Loss on iteration  4 209.0458166444195
Training Loss on iteration  5 209.04581660622574
Training Loss on iteration  6 209.04581656805843
Training Loss on iteration  7 209.0458165299175
Training Loss on iteration  8 209.04581649180292
Training Loss on iteration  9 209.0458164537148
Training Loss on iteration  10 209.04581641565292
Training Loss on iteration  11 209.04581637761746
Training Loss on iteration  12 209.04581633960825
Training Loss on iteration  13 209.04581630162536
Training Loss on iteration  14 209.04581626366874
Training Loss on iteration  15 209.04581622573838
Training Loss on iteration  16 209.04581618783428
Training Loss on iteration  17 209.04581614995635
Training Loss on iteration  18 209.04581611210466
Training Loss on iteration  19 209.04581607427912
Training Loss 

### Observe values of Weight
- Print the updated values

In [34]:
print(w)

tf.Tensor(
[[0.06309611]
 [0.06333528]
 [0.0629523 ]
 [0.06349774]], shape=(4, 1), dtype=float64)


### Observe values of Bias
- Print the updated values

In [35]:
print(b)

tf.Tensor([5.30819226], shape=(1,), dtype=float64)
