# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [2]:
from scipy import stats 
import numpy as np

In [3]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [54]:
#Calculating Mean and Standard deviation
print('Mean is %2.1f Sd is %2.1f' % (GPU1.mean(),np.std(GPU1,ddof = 1)))
print('we reject Null Hypotheiss as the mean is not equal to 0')

Mean is 10.3 Sd is 1.2
we reject Null Hypotheiss as the mean is not equal to 0


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [13]:
from    scipy.stats             import  ttest_1samp,ttest_ind, wilcoxon, ttest_ind_from_stats
import  scipy.stats             as      stats  
from    statsmodels.stats.power import  ttest_power
t_statistic, p_value  =  stats.ttest_ind(GPU1,GPU2)
print('P Value %1.3f' % p_value)
print('Since P value 0.014<0.05 which is much lesser than alpha reject null Hypothesis')

P Value 0.014
Since P value 0.014<0.05 which is much lesser than alpha reject null Hypothesis


## Question 3

He is trying a third GPU - GPU3.

In [14]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [16]:
t_statistic,p_value_new = stats.ttest_ind(GPU1,GPU3)
print('P Value %1.3f'%p_value_new)
print('Since P value 0.145>0.05 which is much greater than alpha fail to reject null Hypothesis and concluded that there is no significant difference between two speeds of two GPUS GPU1 and GPU3')

P Value 0.145
Since P value 0.145>0.05 which is much greater than alpha fail to reject null Hypothesis and concluded that there is no significant difference between two speeds of two GPUS GPU1 and GPU3


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [17]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [24]:
#Levene's test performed on the dataset
print(stats.levene(e1,e2,e3))
print("since pvalue is greater than 0.05 the data set pass through Levene test and conform to the variance criterion")


LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)
since pvalue is greater than 0.05 the data set pass through Levene test and conform to the variance criterion


In [28]:
import pandas as pd
df_experiments = pd.DataFrame()
df_e1 = pd.DataFrame({'Experiment':'1','Results':e1})
df_e2 = pd.DataFrame({'Experiment':'2','Results':e2})
df_e3 = pd.DataFrame({'Experiment':'3','Results':e3})
df_experiments = df_experiments.append(df_e1)
df_experiments = df_experiments.append(df_e2)
df_experiments = df_experiments.append(df_e3)
df_experiments.head(10)

Experiment   Results
0          1  1.595440
1          1  1.419730
2          1  0.000000
3          1  0.000000
0          2  1.433800
1          2  2.079700
2          2  0.892139
3          2  2.384740
0          3  0.036930
1          3  0.938018

In [30]:

import statsmodels.api         as     sm
from   statsmodels.formula.api import ols
mod = ols('Results ~ Experiment', data = df_experiments).fit()
aov_table = sm.stats.anova_lm(mod, typ=2)
print(aov_table)
print('since p value 0.135 is much greater than our chosen level of signifiance at 5% we fail to reject the null hypothesis')
print(' The result shows that the given three experiments are not significantly different')

              sum_sq   df         F    PR(>F)
Experiment  2.399066  2.0  2.513576  0.135746
Residual    4.294994  9.0       NaN       NaN
since p value 0.135 is much greater than our chosen level of signifiance at 5% we fail to reject the null hypothesis
 The result shows that the given three experiments are not significantly different


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [33]:
F,p = stats.f_oneway(e1,e2,e3)
print('F statistic = {:5.3f} and probability p = {:5.3f}'.format(F, p)) 
print('since p value is greater than alpha 0.05 we fail to reject null hypothesis and hence stated that two or more groups have same population mean')

F statistic = 2.514 and probability p = 0.136
since p value is greater than alpha 0.05 we fail to reject null hypothesis and hence stated that two or more groups have same population mean


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

In [34]:
#Type 1 error is the case where rejection of null hypothesis happens and later proves to be true. it is also known as false positive.
#Type 2 error is the case where non rejection of null hypothesis happens and later proves to be false. it is also known as false negative.


## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


#𝜇𝐴𝑓𝑡𝑒𝑟 - Waiting time in past month
#𝜇𝐵𝑒𝑓𝑜𝑟𝑒 - Waiting time in previous months
𝐻0 :  𝜇𝐴𝑓𝑡𝑒𝑟  -  𝜇𝐵𝑒𝑓𝑜𝑟𝑒  = 0
𝐻𝐴 :  𝜇𝐴𝑓𝑡𝑒𝑟  -  𝜇𝐵𝑒𝑓𝑜𝑟𝑒   ≠  0

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [36]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [46]:
chi_sq_stat,p_value,deg_freedom,exp_freq = stats.chi2_contingency(dice)
print('Chi-square statistic %3.5f p value is %1.6f degree of freedom %d' %(chi_sq_stat,p_value,deg_freedom))
print('P value 0.077 is greater than our threshold of 0.01 so we fail to reject the null hypothesis')

Chi-square statistic 23.31567 p value is 0.077664 degree of freedom 15
P value 0.077 is greater than our threshold of 0.01 so we fail to reject the null hypothesis


In [39]:
stats.chi2_contingency(dice)

(23.315671914716496,
 0.07766367301496693,
 15,
 array([[ 5.57419355,  8.20645161,  5.57419355,  4.64516129],
        [ 6.50322581,  9.57419355,  6.50322581,  5.41935484],
        [ 6.73548387,  9.91612903,  6.73548387,  5.61290323],
        [ 6.96774194, 10.25806452,  6.96774194,  5.80645161],
        [ 5.34193548,  7.86451613,  5.34193548,  4.4516129 ],
        [ 4.87741935,  7.18064516,  4.87741935,  4.06451613]]))

## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [42]:
dice_Z =stats.zscore(dice)
dice_Z

array([[-0.46291005, -0.18884739, -1.83711731,  1.44115338],
       [ 1.38873015, -0.64208114,  1.22474487,  0.        ],
       [ 0.9258201 ,  0.7176201 ,  0.61237244, -1.44115338],
       [-0.9258201 ,  1.62408759,  0.61237244, -0.96076892],
       [-1.38873015,  0.03776948,  0.        ,  0.        ],
       [ 0.46291005, -1.54854863, -0.61237244,  0.96076892]])

In [45]:
p_values = stats.norm.sf(abs(dice_Z))
p_values

array([[0.32171442, 0.42510621, 0.03309629, 0.07477068],
       [0.08245741, 0.26041025, 0.11033568, 0.5       ],
       [0.17726974, 0.23649578, 0.27014569, 0.07477068],
       [0.17726974, 0.05217856, 0.27014569, 0.16833418],
       [0.08245741, 0.48493574, 0.5       , 0.5       ],
       [0.32171442, 0.06074513, 0.27014569, 0.16833418]])

## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [47]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [53]:
t_statistic,p_value = stats.ttest_rel(before,after)
print('t statistic is %3.3f and p value is %2.3f'%(t_statistic,p_value))
print("P value is significantly lesser than alpha 0.05 so we reject null hypothesis")
print("As the P value is more or less equal to 0 implies that there is a significant difference before and after weight loss treatment")

t statistic is 5.820 and p value is 0.000
P value is significantly lesser than alpha 0.05 so we reject null hypothesis
As the P value is more or less equal to 0 implies that there is a significant difference before and after weight loss treatment
